# Generated by Django 2.1.2 on 2018-10-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20181015_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('supertype', models.CharField(max_length=255, verbose_name='supertype')),
                ('first_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='first type')),
                ('second_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='second type')),
                ('rarity', models.CharField(max_length=255, verbose_name='typing')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Collection')),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
            },
        ),
    ]
