# Generated by Django 2.1.2 on 2018-10-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20181015_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='number'),
        ),
    ]
