# Generated by Django 2.1.2 on 2018-10-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20181015_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('collection', 'sequence'), 'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
        migrations.AddField(
            model_name='card',
            name='sequence',
            field=models.PositiveIntegerField(null=True, verbose_name='sequence'),
        ),
    ]
